#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl3,  UltraFront,     sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  UltraLeft,      sensorSONAR_inch)
#pragma config(Sensor, dgtl7,  UltraRight,     sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void walkStraight(){
//while(SensorValue[ultrain]>10){
	if ((nMotorEncoder[rightMotor]) > (abs(nMotorEncoder[leftMotor]))){
		motor[rightMotor] = 40;
		motor[leftMotor] = 63;
	}

	if (nMotorEncoder[rightMotor] < abs(nMotorEncoder[leftMotor])){
		motor[rightMotor] = 63;
		motor[leftMotor] = 40;
	}
	if (nMotorEncoder[rightMotor] == abs(nMotorEncoder[leftMotor])){
		motor[rightMotor] = 63;
		motor[leftMotor] = 63;
	}
//}
}
task main()
{

wait1Msec(2000);    //* Wait Start Time
	while(SensorValue[UltraRight]<10){      //* More Than Ten Inches in Front of Robot
		walkStraight();}
while(SensorValue[UltraRight]>10){       //* Less Than Ten Inches in Front of Robot
	motor(rightMotor)=0;
	motor(leftMotor)=0;
}

		wait1Msec(2000);
		motor(rightMotor)=-90;
		motor(leftMotor)=90;
		wait1Msec(660);
		motor(rightMotor)=0;
		motor(leftMotor)=0;
		wait1Msec(1000);


	while(SensorValue[UltraFront]>10){
			walkStraight();}

	while(SensorValue[UltraFront]<10){
			motor(rightMotor)=0;
			motor(leftMotor)=0;}






}
