#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl3,  frontUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  leftUltra,      sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl12, redLed,         sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void goStraight (int leftspeed, int rightspeed){
//this fuction walks straight and has a consistent speed
	motor[rightMotor] = rightspeed;
	motor[leftMotor] = leftspeed;
}

void completeStop (int delaytime){
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(delaytime); //this stops rabot for a delay of time
}

void pointTurn (int leftspeed, int rightspeed, int delaytime){
	motor[rightMotor] = rightspeed;
	motor[leftMotor] = leftspeed;//function to turn
	wait1Msec(delaytime); // continue to reach the desired degree by seconds
}

task main()
{

		int comSpd = 90;
		//int comAdjSpd = 31;
		//int delaySec = 450;
		//int frontSpace = 12; //(46-30)/2
		int rightSpace = 30;

		//wait to have a full stop
		wait1Msec(2000);

		//Right motor is better to use than fwd motor because of different interferences
		while(SensorValue[rightUltra]<rightSpace){
			goStraight(comSpd, comSpd);	//speed is debateable
		}
		completeStop(1000); // have robot stop @ the middle of hallway

		//allow the robot to move a little more, position @ the center of intersection
		goStraight(comSpd, comSpd);
		wait1Msec(600);
		completeStop(500);

		//make 90 turn, going to room#1 direction
		pointTurn(comSpd, -1*comSpd, 1000);//turn to the room so we can almost enter.

		//allow te robot to move forward
		while(SensorValue[frontUltra]>25){
			goStraight(comSpd, comSpd);
		}
		//move close to the wall, and stop, so the robot can stop on the middle of entry
		while(SensorValue[frontUltra]<25){  //when there is no space ahead
			completeStop(1000);	//???
		}

		pointTurn(comSpd, -1*comSpd, 860);//turn into the room 90@Rright turn
		completeStop(1000);

		//drive into the roiom
		while(SensorValue[frontUltra]>30){
			goStraight(comSpd, comSpd);  //Walk straight
		}
		//stop close to 30cm
		if(SensorValue[frontUltra]<35){
			completeStop(1000);
		}

		//180 degree turn
		pointTurn(comSpd, -1*comSpd, 1750);
		completeStop(1000);

		//leave the room
		while(SensorValue[frontUltra]>25){
			goStraight(comSpd, comSpd);
		}
		if(SensorValue[frontUltra]<25){
			completeStop(1000);//exit the room
		}

		//make 90 left turn
		pointTurn(-comSpd, comSpd, 860);
		completeStop(1000);

		goStraight(comSpd, comSpd);// move to center of the hallways
		wait1Msec(1500);



}
