#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl3,  frontUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  leftUltra,      sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  Bumpey,         sensorTouch)
#pragma config(Sensor, dgtl12, redLed,         sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Sensor, in8,    IR_sensor,      sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void walkStraight(int lowSpeed, int CommonSpeed){
//This function Walks straight and has a consistent speed
	if ((nMotorEncoder[rightMotor]) > (abs(nMotorEncoder[leftMotor]))){
		motor[rightMotor] = lowSpeed;
		motor[leftMotor] = CommonSpeed;
	}

	if (nMotorEncoder[rightMotor] < abs(nMotorEncoder[leftMotor])){
		motor[rightMotor] = CommonSpeed;
		motor[leftMotor] = lowSpeed;
	}
	if (nMotorEncoder[rightMotor] == abs(nMotorEncoder[leftMotor])){
		motor[rightMotor] = CommonSpeed;
		motor[leftMotor] = CommonSpeed;
	}
}

void completeStop (int delaytime){
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(delaytime); //this stops rabot for a delay of time
}

void turnRight(int degrees, int speed){
	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[leftMotor]=0;
	//you must reset the encoders

	int tickGoal = (58 * degrees)/10;	//increased the tick goal by 1 today by mattyboio == 74@matt

	motor[leftMotor]=speed;
	motor[rightMotor]=-1*speed;

	while(nMotorEncoder[leftMotor]<tickGoal||nMotorEncoder[rightMotor]>-1*tickGoal){
		if(nMotorEncoder[leftMotor]>tickGoal){
			motor[leftMotor]=0;
		}
		if(nMotorEncoder[rightMotor]<-1*tickGoal){
			motor[rightMotor]=0;
			//this is quality control
		}
	}
}

void turnLeft(int degrees, int speed){
	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[leftMotor]=0;
	//you must reset the encoders

	int tickGoal = (55 * degrees)/10;	//72@Matt

	motor[leftMotor]=-1*speed;
	motor[rightMotor]=speed;

	while(nMotorEncoder[leftMotor]>-1*tickGoal||nMotorEncoder[rightMotor]<tickGoal){
		if(nMotorEncoder[leftMotor]<-1*tickGoal){
			motor[leftMotor]=0;
		}
		if(nMotorEncoder[rightMotor]>tickGoal){
			motor[rightMotor]=0;
			//this is quality control
		}
	}
}

void resetEncoders(){
	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[leftMotor]=0;
}

task main()
{

		int comSpd = 90;
		int lowSpd = 70;
		//int comAdjSpd = 31;
		//int delaySec = 450;
		//int frontSpace = 12; //(46-30)/2
		int rightSpace = 23;
		int senseDog1 = -1;
		int senseDog2 = -1;

		//wait to have a full stop
		while(SensorValue[Bumpey]==0){
			motor[leftMotor]=0;
			motor[rightMotor]=0;
		}
		wait1Msec(500);

		senseDog1 = SensorValue(rightUltra);
		wait1Msec(100);
		senseDog2 = SensorValue(rightUltra);



	//	if(SensorValue(rightUltra)<2*rightSpace){
		if(senseDog1!=senseDog2){ // determines if the doggo is blocking de wae
		//if the dog is there, turn right.
			turnRight(90, 60);
			turnRight(90, 60);

			completeStop(1000);

			//hop like a bonnie rabbit
			resetEncoders();
			walkStraight(lowSpd, comSpd);
			wait1Msec(500);
			completeStop(1000);

			//first leg of da daetour. this is so cool
			resetEncoders();
			while(SensorValue(leftUltra)<rightSpace){
				walkStraight(lowSpd, comSpd);
			}

			//hop like a bonnie wabbit v2
			resetEncoders();
			walkStraight(lowSpd, comSpd);
			wait1Msec(200);
			completeStop(500);

			//self explanitory
			turnLeft(90,60);

			//hop like a wonnie babbit v3
			resetEncoders();
			walkStraight(lowSpd, comSpd);
			wait1Msec(500);
			completeStop(500);

			//second leg of da daetour. this is also so cool
			resetEncoders();
			while(SensorValue(leftUltra)<rightSpace){
				walkStraight(lowSpd, comSpd);
			}

			//vop hike l aonnie wabbit b4
			resetEncoders();
			walkStraight(lowSpd, comSpd);
			wait1Msec(400);
			completeStop(500);

			//solf explanitairy
			turnLeft(90, 60);

			resetEncoders();
			walkStraight(lowSpd, comSpd);
			wait1Msec(500);
			completeStop(500);

			//third leg of dae daetor. t  h  i  s     i  s     a  l  s  o     c  o  o  l
			resetEncoders();
			while(SensorValue(leftUltra)<rightSpace){
				walkStraight(lowSpd, comSpd);
			}

			//bop vike h lonnie aabbit w5
			resetEncoders();
			walkStraight(lowSpd, comSpd);
			wait1Msec(300);
			completeStop(500);

			//eoly sxplanitairf
			turnLeft(90, 60);

			//wop bike v honnie labbit a6
			resetEncoders();
			walkStraight(lowSpd, comSpd);
			wait1Msec(1100);
			completeStop(500);

			//fourth leg of dae daetor. this is also cool FLEX ON DEM HATRS
			//resetEncoders();
			//while(SensorValue(leftUltra)<rightSpace){
			//	walkStraight(lowSpd, comSpd);
			//}

			//solf explanitairy once agian begone
			turnLeft(90, 60);

			resetEncoders();
			while(SensorValue[frontUltra]>27){
				walkStraight(lowSpd, comSpd);//go into the room
			}
			completeStop(1000);
			turnRight(180, 60);
			completeStop(1000);//180 degree scan


		}
	}
