#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
motor[leftmotor]=127;
motor[rightmotor]=127;
wait1Msec(5000);
motor[rightmotor]=127;
motor[leftmotor]=-127;
wait1Msec(1000);
motor[rightmotor]=127;
motor[leftmotor]=127;
wait1Msec(5000);
motor[rightmotor]=127;
motor[leftmotor]=-127;
wait1Msec(1000);
motor[rightmotor]=-127;
motor[rightmotor]=-127;
wait1Msec(5000);


}
