#pragma config(Sensor, dgtl3,  fwdultrain,     sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  Rultrain,      sensorSONAR_cm)
#pragma config(Motor,  port1,           RightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          LeftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard
task main()
{
while(SensorValue[Rultrain]<16){//Right motor is better to use than fwd motor because of different interferences
	motor(RightMotor)=60;
	motor(LeftMotor)=60;
}
while(SensorValue[Rultrain]>16){//Sensor can detect wall better at 16 cm
	motor(RightMotor)=-60;
	motor(LeftMotor)=60;
	wait1Msec(980);//
	motor(RightMotor)=0;
	motor(LeftMotor)=0;
	wait1Msec(1000);//robot needs time to think so I Wait for 1 second
}
while(SensorValue[fwdultrain]>76){
	motor(RightMotor)=60;//using these fwdultrain because the robot only turns because of the right sensor.
	motor(LeftMotor)=60;
}
while(SensorValue[fwdultrain]<76){
	motor(RightMotor)=0;
	motor(LeftMotor)=0;
}
while(SensorValue[Rultrain]<10){
	motor(RightMotor)=60;
	motor(LeftMotor)=60;
}
while(SensorValue[Rultrain]>10){
	motor(RightMotor)=-60;//Turn towards the candle
	motor(LeftMotor)=60;
	wait1Msec(980);
	motor(RightMotor)=0;//Stop to shut the system off
	motor(LeftMotor)=0;
	wait1Msec(1000);
}
while(SensorValue[fwdultrain]>16){
	motor(RightMotor)=60;
	motor(LeftMotor)=60;
}
while(SensorValue[fwdultrain]<16){
	motor(RightMotor)=0;
	motor(LeftMotor)=0;
}
while(SensorValue[fwdultrain]>10){//Move towards the candle after the last turn
	motor(RightMotor)=60;
	motor(LeftMotor)=60;
}
while(SensorValue[fwdultrain]<10){
	motor(RightMotor)=0;
	motor(LeftMotor)=0;
}
motor(RightMotor)=-60;//Needs a 360 degree turn to locate, and then in obliterates
motor(LeftMotor)=60;
wait1Msec(3920);
motor(RightMotor)=0;
motor(LeftMotor)=0;
wait1Msec(10000);
//ANNIHALATE EXODIA OBLITERATE!!!! BOIBOIBOI!!!!! DIDDLY DARN IT, I MISSED!!!! CHARGE UP THE DEATHSTAR!!!!!
//DESTROY ALDERAAN!!!! DIIIIIIEEEEE. AVADA KEDAVRA!!! MASONISWEARTOGAWD
//SOMEBODY TOUCHA MY SPAGHETT!!!
//WHYDIDN'TYOUSHOWUPFORELFPRACTICE?!?!?!?!?!?
//DO YOU KNOW DE WAY
}
