#pragma config(Sensor, dgtl3,  fwdultrain,     sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  Lultrain,       sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  Rultrain,      sensorSONAR_cm)
#pragma config(Motor,  port1,           RightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          LeftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(SensorValue[fwdultrain]>48){
	motor(LeftMotor)=50;
	motor(RightMotor)=50;
}
while(SensorValue[fwdultrain]<48){//*!!SO MANY LOOPS AND BRANCHES OFF OF THIS
	motor(RightMotor)=0;
	motor(LeftMotor)=0;
	wait1Msec(2000);
}
	if(SensorValue[Rultrain]<5){//turn number 1
		motor(RightMotor)=0;
		motor(LeftMotor)=0;
	}
	if(SensorValue[Rultrain]>5){//turn number 1right
		motor(RightMotor)=-60;
		motor(LeftMotor)=60;
		wait1Msec(980);
	}
	while(SensorValue[fwdultrain]>50){
		motor(RightMotor)=60;
		motor(LeftMotor)=60;
	}
	while(SensorValue[fwdultrain]<50){//turn number2 right
		motor(RightMotor)=0;
		motor(LeftMotor)=0;
		wait1Msec(2000);
		motor(RightMotor)=-60;
		motor(LeftMotor)=60;
	}
	while(SensorValue[fwdultrain]>20){
		motor(LeftMotor)=60;
		motor(RightMotor)=60;
	}
	while(SensorValue[fwdultrain]<20){
		motor(RightMotor)=0;
		motor(LeftMotor)=0;
		wait1Msec(2000);
		motor(RightMotor)=-60;
		motor(LeftMotor)=60;//turn 3
	}
	while(SensorValue[fwdultrain]>15){
		motor(LeftMotor)=60;
		motor(RightMotor)=60;
	}
	while(SensorValue[fwdultrain]<15){
		motor(RightMotor)=0;
		motor(LeftMotor)=0;
		wait1Msec(2000);
		//ANNIHALATE. EXODIA, OBLITERATE!!!!!!!!!
	}
}
