 #pragma config(Sensor, dgtl3,  fwdultrain,     sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  Rultrain,      sensorSONAR_cm)
#pragma config(Motor,  port1,           RightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          LeftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard
task main()
{
wait1Msec(2000);
repeat(3){
	while(SensorValue[fwdultrain]>27){
		motor(LeftMotor)=60;
		motor(RightMotor)=50;
	}
	while(SensorValue[fwdultrain]<27){
		motor(LeftMotor)=120;
		motor(RightMotor)=-120;
		wait1Msec(475);
	}
}
}
