#pragma config(Sensor, dgtl3,  fwdultrain,     sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  Lultrain,       sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  Rultrain,      sensorSONAR_cm)
#pragma config(Motor,  port1,           RightMotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          LeftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (SensorValue(fwdultrain)>30){
	motor(LeftMotor)=60;
	motor(RightMotor)=57;
}
while (SensorValue(fwdultrain)<30){
	motor(LeftMotor)=0;
	motor(RightMotor)=0;
	wait1Msec(2000);
	while (SensorValue(Lultrain)>3){
		motor(LeftMotor)=-60;
		motor(RightMotor)=60;
		wait1Msec(980);
	}
	while (SensorValue(Lultrain)<3){
		motor(LeftMotor)=0;
		motor(RightMotor)=0;
	}
	while (SensorValue(Rultrain)>3){
		motor(LeftMotor)=0;
		motor(RightMotor)=0;
		wait1Msec(2000);
	}
	while (SensorValue(Rultrain)<3){
		motor(LeftMotor)=60;
		motor(RightMotor)=-60;
		wait1Msec(980);
	}
}
}
