#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
wait1Msec(2000);
motor[rightMotor]=90;
motor[leftMotor]=-90;
wait1Msec(660);
motor[rightMotor]=0;
motor[leftMotor]=0;


}
