#pragma config(Sensor, dgtl3,  FrontUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  RightUltra,     sensorSONAR_cm)
#pragma config(Motor,  port1,           rightmotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          leftmotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void Pointturn(int leftSpeed, int rightSpeed, int waittime){
	motor[rightmotor]=rightSpeed;
	motor[leftmotor]=leftSpeed;
	wait1Msec(waittime);
	//* easy turns
}

void Straight(int leftval, int rightval){
	motor[rightmotor] = rightval;
	motor[leftmotor] = leftval;
	//* make rightval=63, and leftval=73
	//* To clean up the code
}

void Waitvoid (){
	motor[leftmotor] = 0;
	motor[rightmotor] = 0;
	wait1Msec(1000);
	//* give the robot a rest
}

task main(){
wait1Msec(1000);
while (SensorValue[FrontUltra] > 18 && SensorValue[RightUltra] <= 20){
	Straight(73, 63);
	//* go to the conjunction
}
Waitvoid ();
Pointturn(120, -120, 475);
//* turn
Waitvoid ();
while (SensorValue[FrontUltra]>25){
	Straight(63, 53);
}
//* go to the wall so you can turn into the room
Waitvoid ();
Pointturn (120, -120, 475);
//* turn into the room
Waitvoid ();
while (SensorValue[FrontUltra] > 35){
	Straight(63, 53);
}
//* enter the room
Waitvoid ();
Pointturn(70, -60, 3920);
//* 360 no scope in room
motor(rightmotor) = 0;
motor(leftmotor) = 0;
//* end the code
}
