#pragma config(Sensor, dgtl9,  Bumpey,         sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(SensorValue[Bumpey]==0){
	motor[leftMotor]=0;
	motor[rightMotor]=0;
}

while(SensorValue[Bumpey]==0){
	motor[leftMotor]=63;
	motor[rightMotor]=63;
}

motor[leftMotor]=0;
motor[rightMotor]=0;


}
