#pragma config(Sensor, dgtl3,  ultrain,        sensorSONAR_cm)
#pragma config(Motor,  port1,           rightmotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          leftmotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void Pointturn(int leftSpeed, int rightSpeed, int waittime){
	motor(rightmotor)=rightSpeed;
	motor(leftmotor)=leftSpeed;
	wait1Msec(490);
}

task main()
{
	wait1Msec(1000);
	while (SensorValue(ultrain)>20){
		motor(rightmotor) = 53;
		motor(leftmotor) = 63;
	}
	motor(rightmotor) = 0;
	motor(leftmotor) = 0;
	wait1Msec(1000);
	Pointturn(120, -120, 1000);
	motor(rightmotor) = 0;
	motor(leftmotor) = 0;


}
