#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
wait1Msec(2000);
motor[leftMotor]=-120;
motor[rightMotor]=120;
wait1Msec(490);
motor[leftMotor]=0;
motor[rightMotor]=0;


}
