#pragma config(Sensor, dgtl3,  sonarin,        sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  sonarleft,      sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  sonarright,     sensorSONAR_cm)
#pragma config(Motor,  port1,           rightmotor,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          leftmotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){

	wait1Msec(1000);
while(SensorValue[sonarright]<20){
	motor[leftmotor]=70;
	motor[rightmotor]=60;
	}

while(SensorValue[sonarright]>20){
	motor[leftmotor]=70;
	motor[rightmotor]=-60;
	}

while(SensorValue[sonarin]<15){
	motor[rightmotor]=0;
	motor[leftmotor]=0;
	}

while(SensorValue[sonarin]>20){
	motor[leftmotor]=70;
	motor[rightmotor]=60;}


while(SensorValue[sonarleft]>20)
motor[rightmotor]=-60;
motor[leftmotor]=70;

 while(SensorValue[sonarleft]>20)
motor[rightmotor]=-60;
motor[leftmotor]=70;
}
