#pragma config(Sensor, dgtl3,  frontUltra,        sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  leftUltra,        sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightUltra,     sensorSONAR_cm)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void calculateTickL(){
	  //Reset encoders
		nMotorEncoder[rightMotor] = 0;
		nMotorEncoder[leftMotor] = 0;

  //Some time to unplug the cable from the robot so that it does not interfere with the turning.
  wait1Msec(5000);

  //Perform a point turn to the left. We will use lower power values for more accuracy.
  motor[leftMotor] = -40;
  motor[rightMotor] = 40; // turn left

  //Since the wheels may go at slightly different speeds due to manufacturing tolerances, etc.,
  //we need to test both encoders and control both motors separately. This may result in one motor
  //going for longer than another but it will ultimately result in a much more accurate turn.
  while(nMotorEncoder[rightMotor] < 400 || nMotorEncoder[leftMotor] > -400) {
    if(nMotorEncoder[rightMotor] > 400) {motor[rightMotor] = 0;}
    if(nMotorEncoder[leftMotor] < -400) {motor[leftMotor] = 0;}
  }
}

void calculateTickR(){
	  //Reset encoders
		nMotorEncoder[rightMotor] = 0;
		nMotorEncoder[leftMotor] = 0;

  //Some time to unplug the cable from the robot so that it does not interfere with the turning.
  wait1Msec(5000);

  //Perform a point turn to the left. We will use lower power values for more accuracy.
  motor[leftMotor] = 40;
  motor[rightMotor] = -40; // turn right

  //Since the wheels may go at slightly different speeds due to manufacturing tolerances, etc.,
  //we need to test both encoders and control both motors separately. This may result in one motor
  //going for longer than another but it will ultimately result in a much more accurate turn.
  while(nMotorEncoder[leftMotor] < 420 || nMotorEncoder[rightMotor] > -420) {
    if(nMotorEncoder[leftMotor] > 420) {motor[leftMotor] = 0;}
    if(nMotorEncoder[rightMotor] < -420) {motor[rightMotor] = 0;}
  }
}


task main()
{

	calculateTickR();


}
