#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl3,  frontUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  leftUltra,      sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  Bumpey,         sensorTouch)
#pragma config(Sensor, dgtl10, fan,            sensorDigitalOut)
#pragma config(Sensor, dgtl12, redLed,         sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Sensor, in8,    IR_sensor,      sensorAnalog)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		/*while(SensorValue[Bumpey]==0){
				SensorValue[fan] = 0;
		}
						SensorValue[fan] = 1;
						*/

		SensorValue[redLed] = 1;
		SensorValue[fan] = 0;
		while(true){
					writeDebugStreamLine("IR %d", SensorValue[IR_sensor]);
					if(SensorValue[IR_sensor] > 100){
						SensorValue[fan] = 1;
						SensorValue[redLed] = 0;
					}else{
						SensorValue[fan] = 0;
						SensorValue[redLed] = 1;
					}
		}
}
