#pragma config(Sensor, dgtl10, fan,            sensorDigitalOut)
#pragma config(Sensor, dgtl12, redLed,         sensorDigitalOut)
#pragma config(Sensor, in8,    IR_sensor,      sensorAnalog)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

		/*while(SensorValue[Bumpey]==0){
				SensorValue[fan] = 0;
		}
						SensorValue[fan] = 1;
						*/


		SensorValue[redLed] = 1;
		SensorValue[fan] = 0;
		while(true){
					writeDebugStreamLine("IR %d", SensorValue[IR_sensor]);
					if(SensorValue[IR_sensor] > 100){
						SensorValue[fan] = 1;
						SensorValue[redLed] = 0;
					}else{
						SensorValue[fan] = 0;
						SensorValue[redLed] = 1;
					}
		}
}
