#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void driveOn(int leftSpeed, int rightSpeed, int encoderNum){
	while(nMotorEncoder[rightMotor] < encoderNum){
	//Move forward at half power
		motor[rightMotor] = rightSpeed;
		motor[leftMotor]  = leftSpeed;
	}
}

void completeStop(){
		motor[rightMotor] = 0;
		motor[leftMotor]  = 0;
}

task main(){

	wait1Msec(2000);
	driveOn(63, 63, 800);
	completeStop();
}
