#pragma config(Sensor, dgtl1,  sonarIn,        sensorSONAR_inch)
#pragma config(Motor,  port1,           leftmotor,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x = SensorValue(sonarIn);
	while(true){
		x = SensorValue(sonarIn);
		writeDebugStream("SonarIn is %d", x);
		wait1Msec(2000);
	}
}
