#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl3,  frontUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  leftUltra,      sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  rightUltra,     sensorSONAR_cm)
#pragma config(Sensor, dgtl12, redLed,         sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void calculateTickL(){	//==>412/81
	  //Reset encoders
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);

  //Some time to unplug the cable from the robot so that it does not interfere with the turning.
  wait1Msec(5000);

  //Perform a point turn to the left. We will use lower power values for more accuracy.
  motor[leftMotor] = -40;
  motor[rightMotor] = 40; // turn left

  //Since the wheels may go at slightly different speeds due to manufacturing tolerances, etc.,
  //we need to test both encoders and control both motors separately. This may result in one motor
  //going for longer than another but it will ultimately result in a much more accurate turn.
  while(nMotorEncoder[rightMotor] < 400 || nMotorEncoder[leftMotor] > -400) {
    if(nMotorEncoder[rightMotor] > 400) {motor[rightMotor] = 0;}
    if(nMotorEncoder[leftMotor] < -400) {motor[leftMotor] = 0;}
  }
}

void calculateTickR(){	//==> 440/93
	  //Reset encoders
		resetMotorEncoder(rightMotor);
		resetMotorEncoder(leftMotor);

  //Some time to unplug the cable from the robot so that it does not interfere with the turning.
  wait1Msec(5000);

  //Perform a point turn to the left. We will use lower power values for more accuracy.
  motor[leftMotor] = 40;
  motor[rightMotor] = -40; // turn right

  //Since the wheels may go at slightly different speeds due to manufacturing tolerances, etc.,
  //we need to test both encoders and control both motors separately. This may result in one motor
  //going for longer than another but it will ultimately result in a much more accurate turn.
  while(nMotorEncoder[leftMotor] < 420 || nMotorEncoder[rightMotor] > -420) {
    if(nMotorEncoder[leftMotor] > 420) {motor[leftMotor] = 0;}
    if(nMotorEncoder[rightMotor] < -420) {motor[rightMotor] = 0;}
  }
}

void completeStop(int delay){
		wait1Msec(delay); // allow the car to move forward until the body face open
		motor[rightMotor] = 0;
		motor[leftMotor]  = 0;
}

void encoderReset(){
		//Clear the encoders associated with the left and right motors
		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);
}

void turnRight(int degrees, int speed){
	//fully stop engine
	completeStop(0);
	//Reset encoders
	encoderReset();

  //Determine tickGoal
  int tickGoal = (47 * degrees) / 10;

  //Perform a point turn to the left. We will use lower power values for more accuracy.
  //default 40
  motor[leftMotor] = speed;
  motor[rightMotor] = -1*speed; // turn right

  //Since the wheels may go at slightly different speeds due to manufacturing tolerances, etc.,
  //we need to test both encoders and control both motors separately. This may result in one motor
  //going for longer than another but it will ultimately result in a much more accurate turn.
  while(nMotorEncoder[leftMotor] < tickGoal || nMotorEncoder[rightMotor] > -1*tickGoal) {
    if(nMotorEncoder[leftMotor] > tickGoal) {motor[leftMotor] = 0;}
    if(nMotorEncoder[rightMotor] < -1*tickGoal) {motor[rightMotor] = 0;}
  }
	//turn completed, fully stop engine
	completeStop(0);
}

task main()
{
/*
	wait1Msec(1000);
		motor[rightMotor] = 80;
		motor[leftMotor] = -80;-
	wait1Msec(10000);
				motor[rightMotor] = 0;
		motor[leftMotor] = 0;
		*/
		//calculateTickL();
		//calculateTickR();

		turnRight(90, 40);
}
