#pragma config(Sensor, dgtl12, redLed,         sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

wait1Msec(1000);
SensorValue[redLed] = 0;
wait1Msec(1000);
SensorValue[redLed] = 1;
wait1Msec(1000);
SensorValue[redLed] = 0;
wait1Msec(1000);
SensorValue[redLed] = 1;


}
